# Generated by Django 2.1.1 on 2018-12-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sCourseName', models.CharField(max_length=40)),
                ('m_sCourseUrl', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sName', models.CharField(max_length=80)),
                ('m_sUrl', models.CharField(max_length=80)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_acModules', to='course.Course')),
            ],
        ),
    ]
