# Generated by Django 2.1.1 on 2018-11-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(max_length=80),
        ),
    ]
