
      <div id="mainLeaderboard" style="overflow:hidden;">
        <!-- MainLeaderboard-->

        <!--<pre>main_leaderboard, all: [728,90][970,90][320,50][468,60]</pre>-->
        <div id="snhb-main_leaderboard-0"></div>
       
      </div>
<h1>JavaScript <span class="color_h1">HTML DOM - Changing CSS</span></h1>

<hr>
<p class="intro">The HTML DOM allows JavaScript to change the style of HTML elements.</p>

<hr>
<h2>Changing HTML Style</h2>
<p>To change the style of an HTML element, use this syntax:</p>

<div class="w3-code w3-border notranslate"><div>
document.getElementById(<i>id</i>).style.<i>property </i>=<i> new style</i>
</div></div>

<p>The following example changes the style of a &lt;p&gt; element:</p>

<div class="w3-example">
<h3>Example</h3>
<div class="w3-code notranslate htmlHigh">
&lt;html&gt;<br>
&lt;body&gt;<br><br>
&lt;p id=&quot;p2&quot;&gt;Hello World!&lt;/p&gt;<br>
<br>
&lt;script&gt;<br>
document.getElementById(&quot;p2&quot;).style.color = &quot;blue&quot;;<br>
&lt;/script&gt;<br>
<br>
&lt;p&gt;The paragraph above was changed by a script.&lt;/p&gt;<br>
<br>
&lt;/body&gt;<br>
&lt;/html&gt;
</div>
<a target="_blank" class="w3-btn w3-margin-bottom" href="tryit?filename=tryjs_change_style">Try it Yourself &#xBB;</a>
</div>
<hr>

<h2>Using Events</h2>
<p>The HTML DOM allows you to execute code when an event occurs.</p>
<p>Events are generated by the browser when &quot;things happen&quot; to HTML elements:</p>
<ul>
  <li>An element is clicked on</li>
  <li>The page has loaded</li>
  <li>Input fields are changed</li>
</ul>
<p>You will learn more about events in the next chapter of this tutorial.</p>

<p>This example changes the style of the HTML element with id=&quot;id1&quot;, when the 
user clicks a button:</p>
<div class="w3-example">
<h3>Example</h3>
<div class="w3-code notranslate htmlHigh">
&lt;!DOCTYPE html&gt;<br>&lt;html&gt;<br>&lt;body&gt;<br><br>&lt;h1 id=&quot;id1&quot;&gt;My Heading 1&lt;/h1&gt;<br><br>
&lt;button type=&quot;button&quot; <br>onclick=&quot;document.getElementById(&apos;id1&apos;).style.color = &apos;red&apos;&quot;&gt;<br>
Click Me!&lt;/button&gt;<br><br>&lt;/body&gt;<br>&lt;/html&gt;</div>
<a class="w3-btn w3-margin-bottom" href="tryit?filename=tryjs_dom_color2" target="_blank">Try it Yourself &#xBB;</a>
</div>
<hr>

<h2>More Examples</h2>
<p><a href="tryit?filename=tryjs_visibility" target="_blank">Visibility</a>
How to make an element invisible. Do you want to show the element or not?</p>

<hr>

<h2>HTML DOM Style Object Reference</h2>

<p>For all HTML DOM style properties, look at our complete
<a href="/jsref/dom_obj_style.asp">HTML DOM Style Object Reference</a>.</p>
<hr>

<h2>Test Yourself with Exercises!</h2>
<p>
<a class="w3-btn" href="exercise_js.asp?filename=exercise_js_dom_html6" target="_blank">Exercise 6 &#xBB;</a>&#xA0;
<a class="w3-btn" href="exercise_js.asp?filename=exercise_js_dom_html7" target="_blank">Exercise 7 &#xBB;</a>&#xA0;
<a class="w3-btn" href="exercise_js.asp?filename=exercise_js_dom_html8" target="_blank">Exercise 8 &#xBB;</a>&#xA0;
<!--
<a class="w3-btn" href="exercise.asp?filename=exercise_dom_css1" target="_blank">Exercise 1 &raquo;</a>&nbsp;
<a class="w3-btn" href="exercise.asp?filename=exercise_dom_css2" target="_blank">Exercise 2 &raquo;</a>&nbsp;
<a class="w3-btn" href="exercise.asp?filename=exercise_dom_css3" target="_blank">Exercise 3 &raquo;</a>&nbsp;
<a class="w3-btn" href="exercise.asp?filename=exercise_dom_css4" target="_blank">Exercise 4 &raquo;</a>&nbsp;
<a class="w3-btn" href="exercise.asp?filename=exercise_dom_css5" target="_blank">Exercise 5 &raquo;</a>-->
</p>
<br>


