# Generated by Django 2.1.1 on 2018-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProgress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='id',
        ),
        migrations.AlterField(
            model_name='progress',
            name='m_sCourseUrl',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
